sensors:
    ebpf_sensor:
        exec_path: ./sensors/ebpf
        param: -events=all
        run_as_root: true
        events_header:
            bashReadLine:
                - "PID"
                - "UID"
                - "Username"
                - "CommandLine"
            vfsOpen:
                - "PID"
                - "UID"
                - "Username"
                - "Fullpath"
                - "Flags"
                - "FlagsInterpretation"

exporters:
    # otel:
    #     mode: "file"
    #     destination: "localhost:4317"
    #     timeout: 5
    file:
        mode: "file"
        destination: "./sys.log"
        timeout: 5

# filters:
#     filter_agent:
#         detection:
#             filter_agent:
#                 FileName|contains: "ebpf_sensor"
#             filter_cmd:
#                 CommandLine|endswith: "ebpf_sensor"
#             condition: 1 of filter_*

service:
    description: "Sample test service"
    group: "Sample group"
    pipelines:
        trace_pipe:
            sensors: [ebpf_sensor]
            # filters: [filter_agent]
            exporter: file
        # log_pipe:
        #     sensors: [ebpf_sensor]
        #     exporter: opensearch
