sensors:
    ebpf_sensor:
        exec_path: /home/shhong/Desktop/POLVO/polvo/sensors/ebpf
        param: -events=all
        run_as_root: true
        events_header:
            bashReadLine:
                - "PID"
                - "UID"
                - "Username"
                - "CommandLine"
            vfsOpen:
                - "PID"
                - "UID"
                - "Username"
                - "Fullpath"
                - "Flags"
                - "FlagsInterpretation"

exporters:
    # otel:
    #     mode: "file"
    #     destination: "localhost:4317"
    #     timeout: 5
    file:
        mode: "file"
        destination: "./sys.log"
        timeout: 5

service:
    description: "Sample test service"
    group: "Sample group"
    pipelines:
        trace_pipe:
            sensors: [ebpf_sensor]
            exporter: file
        # log_pipe:
        #     sensors: [ebpf_sensor]
        #     exporter: opensearch
